"""refactor student profile with modular tables

Revision ID: 03e2f2a3ddbc
Revises: e04950fcf918
Create Date: 2026-02-13 14:59:29.823687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '03e2f2a3ddbc'
down_revision: Union[str, None] = 'e04950fcf918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'MONK', name='maritalstatus'), nullable=True),
    sa.Column('birth_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_woreda', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_kebele', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_woreda', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_kebele', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('ELEMENTARY', 'HIGH_SCHOOL', 'PREPARATORY', 'HIGHER_EDUCATION', 'ILLITERATE', name='educationlevel'), nullable=True),
    sa.Column('occupation', sa.Enum('STUDENT', 'EMPLOYED_CIVIL', 'EMPLOYED_PRIVATE', 'WORKER_AND_STUDENT', 'UNEMPLOYED', 'SELF_EMPLOYED', name='occupationstatus'), nullable=True),
    sa.Column('college_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('father_alive', sa.Boolean(), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_dob', sa.Date(), nullable=True),
    sa.Column('father_pob', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_education_level', sa.Enum('ELEMENTARY', 'HIGH_SCHOOL', 'PREPARATORY', 'HIGHER_EDUCATION', 'ILLITERATE', name='educationlevel'), nullable=True),
    sa.Column('father_disability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_alive', sa.Boolean(), nullable=False),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_dob', sa.Date(), nullable=True),
    sa.Column('mother_pob', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mother_education_level', sa.Enum('ELEMENTARY', 'HIGH_SCHOOL', 'PREPARATORY', 'HIGHER_EDUCATION', 'ILLITERATE', name='educationlevel'), nullable=True),
    sa.Column('mother_disability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parents_have_spiritual_father', sa.Boolean(), nullable=False),
    sa.Column('parents_spiritual_visit_freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parents_church_freq', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'OCCASIONALLY', 'NEVER', name='churchattendance'), nullable=True),
    sa.Column('orthodox_awareness_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family_members_living_together', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('disability_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_trauma', sa.Boolean(), nullable=False),
    sa.Column('trauma_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('health_issues', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mental_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_spirituality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('baptism_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('baptism_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_spiritual_father', sa.Boolean(), nullable=False),
    sa.Column('spiritual_father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spiritual_father_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_holy_orders', sa.Boolean(), nullable=False),
    sa.Column('joined_sunday_school_date', sa.Date(), nullable=True),
    sa.Column('reason_for_joining', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE maritalstatus AS ENUM ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'MONK');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE educationlevel AS ENUM ('ELEMENTARY', 'HIGH_SCHOOL', 'PREPARATORY', 'HIGHER_EDUCATION', 'ILLITERATE');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE occupationstatus AS ENUM ('STUDENT', 'EMPLOYED_CIVIL', 'EMPLOYED_PRIVATE', 'WORKER_AND_STUDENT', 'UNEMPLOYED', 'SELF_EMPLOYED');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE churchattendance AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'OCCASIONALLY', 'NEVER');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE studentcategory AS ENUM ('CHILDREN', 'ADOLESCENT', 'YOUTH', 'ADULT');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)


    op.add_column('students', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('students', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
    op.add_column('students', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.drop_column('students', 'church')
    op.drop_column('students', 'name')
    op.drop_column('students', 'sex')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'age')
    op.drop_column('students', 'profile_data')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('church', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'dob')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'full_name')
    op.drop_table('student_spirituality')
    op.drop_table('student_health')
    op.drop_table('student_family')
    op.drop_table('student_education')
    op.drop_table('student_addresses')
    # ### end Alembic commands ###

