"""Add FLS and profile builder to departments

Revision ID: 08fb81b3624b
Revises: 0dcd095c54dd
Create Date: 2026-02-27 22:44:25.117209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fb81b3624b'
down_revision: Union[str, None] = '0dcd095c54dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_profile_builder', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('departments', sa.Column('allowed_student_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'allowed_student_fields')
    op.drop_column('departments', 'is_profile_builder')
    # ### end Alembic commands ###

