"""add_attendance_tables_complete

Revision ID: 2466e4a79a51
Revises: b7c74dc2e35b
Create Date: 2026-01-31 19:08:14.952472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2466e4a79a51'
down_revision: Union[str, None] = 'b7c74dc2e35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

