"""Add church field to student

Revision ID: 25ff3143f27f
Revises: 99ffbc776f15
Create Date: 2026-03-25 22:58:56.941134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ff3143f27f'
down_revision: Union[str, None] = '99ffbc776f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('church', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'church')
    # ### end Alembic commands ###

