"""Add programs table and is_active flag

Revision ID: 302bdfbcb204
Revises: 03e2f2a3ddbc
Create Date: 2026-02-27 15:48:41.854529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302bdfbcb204'
down_revision: Union[str, None] = '03e2f2a3ddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('is_active', sa.Boolean(), server_default='true',nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'is_active')
    # ### end Alembic commands ###

