"""Add qr_token to students

Revision ID: 99ffbc776f15
Revises: 08fb81b3624b
Create Date: 2026-03-25 21:10:16.807298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ffbc776f15'
down_revision: Union[str, None] = '08fb81b3624b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('qr_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_qr_token'), 'students', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_qr_token'), table_name='students')
    op.drop_column('students', 'qr_token')
    # ### end Alembic commands ###

